name: Build
on: [push]
jobs:
  platform-independent:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Graal JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Compile and package
      run: mvn package
    - name: Run projects
      run: |
        java -jar multijar/target/multijar-*.jar
        java -jar fat-jar/target/fat-jar-*jar-with-dependencies.jar
        java -p exploded/target/app -m packaging.exploded/io.github.danthe1st.mavenpackaging.exploded.ExplodedMain
    - name: Upload multijar
      uses: actions/upload-artifact@v4
      with:
        name: multijar
        path: |
          multijar/target/multijar-*.jar
          multijar/target/app/
    - name: Upload fat JAR
      uses: actions/upload-artifact@v4
      with:
        name: fat-jar
        path: fat-jar/target/fat-jar-*jar-with-dependencies.jar
    - name: Upload exploded archive
      uses: actions/upload-artifact@v4
      with:
        name: exploded
        path: exploded/target/app
  platform-dependent:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          os_name: linux
          jpackage_install: sudo apt install -y ./jpackage/target/package/myapp_1.0.0_amd64.deb
          jpackage_run: /opt/myapp/bin/myapp
        - os: windows-latest
          os_name: windows
          jpackage_install: Start-Process msiexec.exe -Wait -ArgumentList '/i /quiet jpackage\\target\\package\\myapp-1.0.0.msi"
          jpackage_run: 'ls $env:LOCALAPPDATA ; ls "C:\\Program Files" ; . "C:\\Program Files\\myapp\\bin\\app.exe"'
        - os: macos-latest
          os_name: macos
          jpackage_install: hdiutil attach ./jpackage/target/package/myapp-1.0.0.dmg
          jpackage_run:  /Volumes/myapp/myapp.app/Contents/MacOS/myapp
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Graal JDK
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm-community'
        java-version: '21'
        cache: 'maven'
    - name: Compile and package
      run: mvn package -Penable-native-image
    - name: Install jpackage
      run: ${{ matrix.jpackage_install }}
    - name: Run projects
      run: |
        jlink/target/maven-jlink/default/bin/run
        native-image/target/native-image
        ${{ matrix.jpackage_run }}
    - name: Upload jlink
      uses: actions/upload-artifact@v4
      with:
        name: jlink-${{ matrix.os }}
        path: jlink/target/jlink-*.zip
    - name: Upload native-image
      uses: actions/upload-artifact@v4
      with:
        name: native-image-${{ matrix.os_name }}
        path: |
          native-image/target/native-image
          native-image/target/native-image.exe
    - name: Upload jpackage
      uses: actions/upload-artifact@v4
      with:
        name: jpackage-${{ matrix.os_name }}
        path: jpackage/target/package/*